### ISSUE TITLE
A Nyomtatás gomb nem működik

### ISSUE THREAD

**Issue by ggubacsi** [vszakats/cibib-app#1]
Ha a Java appletben a Nyomtatásra kattintok, nem történik semmi (Firefox alatt, amikor még működött a netbank, ilyenkor behozta a nyomtatandó doksi előnézetét.)
Tudsz esetleg segíteni, mi a teendő?

**Comment by vszakats** [comment]
Sajnos ismert probléma, amire nem sikerült megoldást találni a böngészőn kívüli üzemmódban. Nincs jobb ötletem míg megvárni a remélhetőleg idén/hamarosan megérkező, Java nélkül működő, böngészős netbankot.

**Comment by ggubacsi** [comment]
Köszi a gyors választ.
Tegnapig Firefox alatt legalább működött, de ma vmi miatt el sem indul az Applet, egyből behozza azt az oldalt, amit Chrome alatt is (ohgy töltsem le a jnlp-t, ami pedig szintén nem működik.)  Közben a banki kivonatokat kellene valahogy pdf-ben levarázsolnom…  Tudsz esetleg valami workaround-ot?  (A txt-s export és pdf-es átalakítás a dok. szélességek beállítása miatt elég nehézkes, ráadásul az egyéb nyomtatási feladatoknál – pl. utalási visszaigazolás – nem is működik.)

Üdv.

Gergő

**Comment by vszakats** [comment]
Sajnos nem tudok workaroundot, több ügyfélszolgálati kör után sem. Safari alól soha nem működött a nyomtatás (sem a link megnyitás). Ami viszont igen, az az Export gomb, úgyhogy ahol van ilyen (pl. számlatörténet), azt használom, és ez működik JNLP-s módban is. A többire pedig maradt a papír.

**Comment by ggubacsi** [comment]
Jaja… viszont FIrefox alatt működött .  És most már windows (Parallels) alatt sem.  Vajon miért?

**Comment by vszakats** [comment]
Nem tudom megmondani, elképzelhető, hogy a böngésző frissült, vagy szerver-oldalon kezdték el elbontani a régi holmikat.

A Firefox 1 hete megjelent 52-es verziója már egyáltalán nem engedi futni a Java-t: https://www.mozilla.org/en-US/firefox/52.0/releasenotes/
